pipeline {

   agent none

   stages {
      stage('build') {
         agent {
             docker {
                 image 'python:2.7.16-slim'
                 args '-u root --env http_proxy="http://172.17.7.137:3129/" --env  https_proxy="http://172.17.7.137:3129/"'
               }
         }
         when{
           changeset "**/vote/**"
         }
         steps {
            echo 'Compiling vote app'
            dir('vote'){
              //sh 'python -m pip install --upgrade pip'
              sh 'pip install -r requirements.txt'
            }
         }
      }
      
      stage('test') {
         agent {
             docker {
                 image 'python:2.7.16-slim'
                 args '-u root --env http_proxy="http://172.17.7.137:3129/" --env  https_proxy="http://172.17.7.137:3129/"'
               }
         }
         when{
          changeset "**/vote/**"
         }
         steps {
            echo 'Running Unit Tests on vote app'
            dir('vote'){
              sh 'nosetests -v'
            }            
         }
      }
      stage('docker-package') {
         agent any
         when{
           changeset "**/vote/**"
           branch 'master'
         }
         steps {
            echo 'Building vote app with docker'
            script{
              docker.withRegistry('https://index.docker.io/v1/','dockerhublogin'){
                def workerImage = docker.build("ksa75/vote:v${env.BUILD_ID}","./vote")
                workerImage.push()
                workerImage.push("${env.BRANCH_NAME}")

              }
            }
         }
      }
   }
   post{
       always{
           echo 'Build pipeline for vote is completed'
       }
       failure{
         slackSend (channel: "instavote-cd", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>))")
       }
       success{
         slackSend (channel: "instavote-cd", message: "Build Succeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>))")
           
       }
   }
}
