pipeline {

   agent {
       docker {
           image 'python:2.7.16-slim'
           args '--env http_proxy="http://172.17.7.137:3129/" --env  https_proxy="http://172.17.7.137:3129/"'
         }
   }


   stages {
      stage('build') {
         when{
           changeset "**/vote/**"
         }
         steps {
            echo 'Compiling vote app'
            dir('vote'){
              sh 'pip install -i requirements.txt'
            }
         }
      }
      
      stage('test') {
         when{
          changeset "**/vote/**"
         }
         steps {
            echo 'Running Unit Tests on vote app'
            dir('worker'){
              sh 'nosetests -v'
            }            
         }
      }
   }
   post{
       always{
           echo 'Build pipeline for vote is completed'
       }
       failure{
         slackSend (channel: "instavote-cd", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>))")
       }
       success{
         slackSend (channel: "instavote-cd", message: "Build Succeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>))")
           
       }
   }
}
