vote:
  image: ksa75/vote:master
  ports:
    - 5000:80
  links:
    - redis:redis

redis:
  image: redis:alpine

db:
  image: postgres:latest
  environment:
     POSTGRES_DB: "db"
     POSTGRES_HOST_AUTH_METHOD: "trust"
  

result:
  image: ksa75/result:master
  ports:
    - 5001:80
  links:
    - db:db

worker:
  image: ksa75/worker:master
  links:
    - redis:redis
    - db:db
