vote:
  image: ksa75/vote:master
  ports:
    - 5000:80
  links:
    - redis:redis

redis:
  image: redis:alpine

db:
  image: postgres:latest

result:
  image: ksa75/result:master
  ports:
    - 5001:4000
  links:
    - db:db

worker:
  image: ksa75/worker:master
  links:
    - redis:redis
    - db:db
