pipeline {
   agent any

   tools{
    maven 'Maven 3.6.3'
   }

   stages {
      stage('build') {
         when{
           changeset "**/worker/**"
         }
         steps {
            echo 'Compiling worker app'
            dir('worker'){
              sh 'mvn compile'
            }
         }
      }
      
      stage('test') {
         when{
          changeset "**/worker/**"
         }
         steps {
            echo 'Running Unit Tests on worker app'
            dir('worker'){
              sh 'mvn clean test'
            }            
         }
      }
      
      stage('package') {
         when{
           branch "master"
           changeset "**/worker/**"
         }
         steps {
            echo 'Building worker app'
            dir('worker'){
              sh 'mvn package -Dskiptests'
            }            
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
         }
      }
   }
   post{
       always{
           echo 'Build pipeline for worker is completed'
           
       }
   }
}
